import re

# blocklist.py — Adult Domain & Keyword Blocklist
# This file contains adult domains and browser-title keywords to detect/block

ADULT_KEYWORDS = [
    # Live Adult TV & IPTV terms
    "adult tv", "live adult tv", "adult iptv", "adult live stream",
    "hustler tv", "hustler hd", "blue hustler", "playboy tv", "playboy hd",
    "vivid red", "vivid-red", "vividred", "vivid touch", "vivid tv", "vivid hd",
    "vivid anime", "vivid black", "vivid celeb", "vivid 24", "vivid live",
    "dorcel tv", "dorcel hd", "redlight tv", "redlight hd",
    "penthouse tv", "penthouse passion", "penthouse gold", "penthouse hd",
    "brazzers tv", "xxl tv", "xxl hd", "babestation",
    "studio 66 tv", "television x", "channel 69", "adult channel",
    "live sex tv", "live porn tv", "adult iptv m3u", "adult stream live",
    "adult cable tv", "porno tv live", "sex tv live", "adult stream",
    "adult live video", "erotic tv", "nude tv", "live erotic tv",
    "pink o tv", "satisfaction tv", "french lover tv", "exotica tv", "exotica hd",
    "man-x tv", "dusk tv", "cento x cento tv", "barely legal tv",
    "adult streaming tv", "iptv adult list", "iptv xxx", "xxx iptv",
    "private tv", "private hd", "sct tv", "sct hd", "freex tv", "xdream tv",
    "sexysat", "leotv", "superone", "daring tv", "okteve",

    # Core explicit terms
    "porn", "porno", "pornography", "pornographic",
    "xxx", "x-rated", "xrated",
    "adult content", "adult site", "adult video",
    "nude", "nudity", "naked", "nudist",
    "sex", "sexy", "sexual", "sexuality",
    "erotic", "erotica", "erotic content",
    "hentai", "anime porn", "manga porn",
    "milf", "gilf", "dilf",
    "masturbat", "masturbation",
    "orgasm", "ejaculat",
    "penis", "vagina", "vulva", "genitalia", "genital",
    "boobs", "boob", "tits", "titties", "breast",
    "ass", "butt", "buttocks", "anus",
    "cock", "dick", "phallus",
    "pussy", "cunt",
    "blowjob", "blow job", "handjob", "hand job",
    "cumshot", "cum shot", "creampie", "cream pie",
    "gangbang", "gang bang",
    "threesome", "foursome",
    "orgy",
    "bdsm", "bondage", "dominatrix", "submissive",
    "fetish", "kinky", "kink",
    "stripper", "striptease", "strip tease",
    "escort", "prostitut", "hooker",
    "camgirl", "cam girl", "webcam sex",
    "onlyfans", "only fans",
    "sexting",
    "naughty", "dirty video",
    "lesbian porn", "gay porn", "bi porn",
    "amateur porn", "teen porn",
    "shemale", "tranny", "transsexual porn",
    "interracial", "ebony porn",
    "asian porn", "latina porn",
    "hardcore", "softcore",
    "free porn", "watch porn",
    "hot naked", "naked girls", "naked women",
    "nude girls", "nude women", "nude men",
    "big tits", "big boobs", "big ass",
    "hot sex", "sex video", "sex tape",
    "fuck", "fucking", "fucker",
    "shit", "fap", "fapping",
    "jerk off", "jerkoff",
    "squirt", "squirting",
    "anal", "anal sex",
    "oral sex", "cunnilingus", "fellatio",
    "deepthroat", "deep throat",
    "doggystyle", "doggy style",
    "cowgirl position",
    "69 position",
    "hot model nude",
    "xvideos", "xhamster", "pornhub", "xnxx", "redtube",
    "youporn", "tube8", "spankbang", "chaturbate",
]

# Known adult domains — 500+ major domains
ADULT_DOMAINS = [
    # ── Tier 0: Live Adult TV & Adult IPTV Platforms ──
    "okteve.com", "www.okteve.com",
    "playboytv.com", "www.playboytv.com",
    "hustler.com", "www.hustler.com", "hustlertv.com", "www.hustlertv.com",
    "dorcel.com", "www.dorcel.com", "dorceltv.com", "www.dorceltv.com",
    "redlighttv.com", "www.redlighttv.com",
    "bluehustler.com", "www.bluehustler.com",
    "vividtv.com", "www.vividtv.com",
    "penthousetv.com", "www.penthousetv.com",
    "xxltv.com", "www.xxltv.com",
    "babestation.tv", "www.babestation.tv", "babestation.co.uk",
    "studio66tv.com", "www.studio66tv.com",
    "televisionx.com", "www.televisionx.com",
    "adultchannel.com", "www.adultchannel.com",
    "man-x.tv", "www.man-x.tv",
    "exoticatv.com", "www.exoticatv.com",
    "frenchlover.tv", "www.frenchlover.tv",
    "adultiptv.net", "www.adultiptv.net",
    "adultiptv.com", "www.adultiptv.com",
    "adultiptv4k.com", "www.adultiptv4k.com",
    "adultiptvpremium.com", "www.adultiptvpremium.com",
    "adultiptv.org", "www.adultiptv.org",
    "adultiptv.store", "www.adultiptv.store",
    "freeadultiptv.com", "www.freeadultiptv.com",
    "livetvadult.com", "www.livetvadult.com",
    "livetvsex.com", "www.livetvsex.com",
    "adultlivetv.com", "www.adultlivetv.com",
    "adulttvchannels.com", "www.adulttvchannels.com",
    "adultstream.tv", "www.adultstream.tv",
    "adultstream.net", "www.adultstream.net",
    "adultstream.com", "www.adultstream.com",
    "adulttvlive.com", "www.adulttvlive.com",
    "adult-iptv.com", "www.adult-iptv.com",
    "adult-iptv.net", "www.adult-iptv.net",
    "iptvadult.net", "www.iptvadult.net",
    "iptv-adult.com", "www.iptv-adult.com",
    "iptvadult24.com", "www.iptvadult24.com",
    "xxx-iptv.com", "www.xxx-iptv.com",
    "iptvxxx.com", "www.iptvxxx.com",
    "xxxiptv.net", "www.xxxiptv.net",
    "adultiptvlist.com", "www.adultiptvlist.com",
    "freeadulttv.net", "www.freeadulttv.net",
    "adultwebcam.tv", "www.adultwebcam.tv",
    "liveadulttv.net", "www.liveadulttv.net",
    "adultstreamers.com", "www.adultstreamers.com",
    "livecamtv.com", "www.livecamtv.com",
    "liveboobstv.com", "www.liveboobstv.com",
    "livesextv.com", "www.livesextv.com",

    # ── Tier 1: Major tube sites ──
    "pornhub.com", "www.pornhub.com",
    "xvideos.com", "www.xvideos.com", "xvideos2.com",
    "xhamster.com", "www.xhamster.com", "xhamster2.com", "xhamster3.com",
    "xnxx.com", "www.xnxx.com",
    "redtube.com", "www.redtube.com",
    "youporn.com", "www.youporn.com",
    "tube8.com", "www.tube8.com",
    "spankbang.com", "www.spankbang.com",
    "txxx.com", "www.txxx.com",
    "hclips.com", "www.hclips.com",
    "porntrex.com", "www.porntrex.com",
    "tnaflix.com", "www.tnaflix.com",
    "vporn.com", "www.vporn.com",
    "pornone.com", "www.pornone.com",
    "bravotube.net", "www.bravotube.net",
    "drtuber.com", "www.drtuber.com",
    "4tube.com", "www.4tube.com",
    "slutload.com", "www.slutload.com",
    "sunporno.com", "www.sunporno.com",
    "anyporn.com", "www.anyporn.com",
    "pornerbros.com", "www.pornerbros.com",
    "gotporn.com", "www.gotporn.com",
    "viptube.com", "www.viptube.com",
    "hdtube.porn",
    "porntube.com", "www.porntube.com",
    "porn.com", "www.porn.com",
    "sex.com", "www.sex.com",
    "xxx.com", "www.xxx.com",
    "fuck.com", "www.fuck.com",
    "cum.com",
    "bigtits.com",

    # ── Tier 2: Premium/pay sites ──
    "brazzers.com", "www.brazzers.com",
    "naughtyamerica.com", "www.naughtyamerica.com",
    "realitykings.com", "www.realitykings.com",
    "bangbros.com", "www.bangbros.com",
    "mofos.com", "www.mofos.com",
    "digitalplayground.com", "www.digitalplayground.com",
    "wicked.com", "www.wicked.com",
    "kink.com", "www.kink.com",
    "teamskeet.com", "www.teamskeet.com",
    "nubiles.net", "www.nubiles.net",
    "passion-hd.com", "www.passion-hd.com",
    "mommysgirl.com", "www.mommysgirl.com",
    "girlsway.com", "www.girlsway.com",
    "sweetheartvideo.com", "www.sweetheartvideo.com",
    "penthouse.com", "www.penthouse.com",
    "playboy.com", "www.playboy.com",
    "hustler.com", "www.hustler.com",

    # ── Tier 3: Cam/live sites ──
    "chaturbate.com", "www.chaturbate.com",
    "livejasmin.com", "www.livejasmin.com",
    "myfreecams.com", "www.myfreecams.com",
    "cam4.com", "www.cam4.com",
    "bongacams.com", "www.bongacams.com",
    "streamate.com", "www.streamate.com",
    "imlive.com", "www.imlive.com",
    "flirt4free.com", "www.flirt4free.com",
    "camsoda.com", "www.camsoda.com",
    "stripchat.com", "www.stripchat.com",
    "jasmin.com", "www.jasmin.com",
    "joyourself.com", "www.joyourself.com",
    "cams.com", "www.cams.com",
    "xcams.com", "www.xcams.com",
    "camcontacts.com", "www.camcontacts.com",
    "camster.com", "www.camster.com",
    "omegle.com", "www.omegle.com",
    "shagle.com", "www.shagle.com",

    # ── Tier 4: OnlyFans & creator platforms ──
    "onlyfans.com", "www.onlyfans.com",
    "fansly.com", "www.fansly.com",
    "manyvids.com", "www.manyvids.com",
    "clips4sale.com", "www.clips4sale.com",
    "iwantclips.com", "www.iwantclips.com",
    "loyalfans.com", "www.loyalfans.com",
    "admireme.vip", "www.admireme.vip",
    "fancentro.com", "www.fancentro.com",
    "justforfans.com", "www.justforfans.com",
    "modelcentro.com", "www.modelcentro.com",

    # ── Tier 5: Hentai & anime adult ──
    "nhentai.net", "www.nhentai.net",
    "hentaihaven.xxx",
    "hentai.tv", "www.hentai.tv",
    "fakku.net", "www.fakku.net",
    "doujins.com", "www.doujins.com",
    "hentaifox.com", "www.hentaifox.com",
    "hentaimama.io",
    "hentairead.com", "www.hentairead.com",
    "hentai2read.com", "www.hentai2read.com",
    "hentaiera.com", "www.hentaiera.com",
    "hentaigasm.com",
    "tsumino.com", "www.tsumino.com",
    "luscious.net", "www.luscious.net",
    "imhentai.xxx",
    "simply-hentai.com", "www.simply-hentai.com",
    "hanime.tv", "www.hanime.tv",

    # ── Tier 6: Gay/LGBT adult ──
    "gayporn.com",
    "gaymaletube.com", "www.gaymaletube.com",
    "pornhub.com/gay",
    "men.com", "www.men.com",
    "theguysite.com", "www.theguysite.com",
    "gayroom.com", "www.gayroom.com",
    "xtube.com", "www.xtube.com",
    "rawboyz.com",
    "nextdoorstudios.com", "www.nextdoorstudios.com",
    "paperview.tv",
    "seancody.com", "www.seancody.com",
    "corbin fisher.com",
    "belami.online",
    "bel ami online.com",

    # ── Tier 7: Escort/dating adult ──
    "adultfriendfinder.com", "www.adultfriendfinder.com",
    "ashley madison.com",
    "ashleymadison.com", "www.ashleymadison.com",
    "seeking.com", "www.seeking.com",
    "sugardaddy.com", "www.sugardaddy.com",
    "xmatch.com", "www.xmatch.com",
    "flirt.com", "www.flirt.com",
    "naughtydate.com", "www.naughtydate.com",
    "fuckbook.com", "www.fuckbook.com",
    "instabang.com", "www.instabang.com",
    "nostringsattached.com", "www.nostringsattached.com",
    "swingtowns.com", "www.swingtowns.com",
    "kasidie.com", "www.kasidie.com",
    "alt.com", "www.alt.com",
    "bdsm.com", "www.bdsm.com",
    "fetlife.com", "www.fetlife.com",

    # ── Tier 8: Image boards & galleries ──
    "rule34.xxx", "www.rule34.xxx",
    "rule34.paheal.net",
    "e621.net", "www.e621.net",
    "gelbooru.com", "www.gelbooru.com",
    "danbooru.donmai.us",
    "sankakucomplex.com", "www.sankakucomplex.com",
    "chan.sankakucomplex.com",
    "idol.sankakucomplex.com",
    "xbooru.com", "www.xbooru.com",
    "rule34.booru.org",
    "tbib.org", "www.tbib.org",
    "hypnohub.net", "www.hypnohub.net",

    # ── Tier 9: Additional tubes and aggregators ──
    "beeg.com", "www.beeg.com",
    "empflix.com", "www.empflix.com",
    "freeones.com", "www.freeones.com",
    "iafd.com", "www.iafd.com",
    "adultdvdtalk.com", "www.adultdvdtalk.com",
    "pornmd.com", "www.pornmd.com",
    "porndig.com", "www.porndig.com",
    "pornhd.com", "www.pornhd.com",
    "eporner.com", "www.eporner.com",
    "alphaporno.com", "www.alphaporno.com",
    "vjav.com", "www.vjav.com",
    "javhd.com", "www.javhd.com",
    "javmost.com", "www.javmost.com",
    "dmm.co.jp",
    "javbus.com", "www.javbus.com",
    "javbangers.com",
    "r18.com", "www.r18.com",
    "javfinder.com",
    "bravoteens.com",
    "yobt.com", "www.yobt.com",
    "cumlouder.com", "www.cumlouder.com",
    "ixxx.com", "www.ixxx.com",
    "pornzog.com", "www.pornzog.com",
    "ahegao.xxx",
    "pornkai.com", "www.pornkai.com",
    "youjizz.com", "www.youjizz.com",
    "fux.com", "www.fux.com",
    "pichunter.com", "www.pichunter.com",
    "sexvid.xxx",
    "cliphunter.com", "www.cliphunter.com",
    "hellporno.com", "www.hellporno.com",
    "porndoe.com", "www.porndoe.com",
    "desixnxx.net",
    "indianporn.com",
    "desi52.com",
    "pornwex.tv",
    "shesfreaky.com", "www.shesfreaky.com",
    "worldstarhiphop.com",
    "pornhub.org",
    "fullpornnetwork.com",

    # ── Tier 10: More known adult sites ──
    "motherless.com", "www.motherless.com",
    "godofporn.com",
    "hornbunny.com", "www.hornbunny.com",
    "nudevista.com", "www.nudevista.com",
    "fap18.net", "www.fap18.net",
    "fapvid.com",
    "faphouse.com", "www.faphouse.com",
    "faperoni.com",
    "fapnado.com",
    "fapality.com",
    "fapper.net",
    "porntop.com",
    "jizzbunker.com", "www.jizzbunker.com",
    "jizzhut.com",
    "wankoz.com", "www.wankoz.com",
    "maturetube.com", "www.maturetube.com",
    "silvermature.com",
    "bravomatures.com",
    "milfzr.com",
    "matureporn.com",
    "milfporn.com",
    "olderporntubes.com",
    "40somethinmag.com",
    "sweetmilf.net",
    "momxxx.com", "www.momxxx.com",
    "mompov.com", "www.mompov.com",
    "momsbangteens.com",
    "mommyblowsbest.com",
    "momsondemand.com",
    "maturenl.com",
    "teenporn.com",
    "teensexmania.com",
    "18only.net",
    "teens-analyzed.com",
    "tightteens.net",
    "18onlygirls.com",
    "skinny-teen.com",
    "collegeporn.com",
    "college-party-xxx.com",
    "publicpickups.com",
    "realityjunkies.com",
    "privatespecials.com",
    "frolicme.com",
    "hegre.com", "www.hegre.com",
    "hegreaart.com",
    "beautiful-pussy.com",
    "abbywinters.com", "www.abbywinters.com",
    "zishy.com", "www.zishy.com",
    "babes.com", "www.babes.com",
    "met-art.com", "www.met-art.com",
    "metart.com", "www.metart.com",
    "watch4beauty.com", "www.watch4beauty.com",
    "femjoy.com", "www.femjoy.com",
    "domai.com", "www.domai.com",
    "joymii.com", "www.joymii.com",
    "thelifeerotic.com",
    "skokka.com", "www.skokka.com",
    "adultwork.com", "www.adultwork.com",
    "erosguide.com", "www.erosguide.com",
    "cityxguide.com",
    "slixa.com", "www.slixa.com",
    "listcrawler.com", "www.listcrawler.com",
    "rubmaps.com", "www.rubmaps.com",
    "nightshift.cc",
    "pornbb.org", "www.pornbb.org",
    "thehun.com", "www.thehun.com",
    "yuvutu.com", "www.yuvutu.com",
    "heavy-r.com", "www.heavy-r.com",
    "rude.com", "www.rude.com",
    "swallowed.com", "www.swallowed.com",
    "wifebucket.com", "www.wifebucket.com",
    "cuckold.com",
    "amateur.tv",
    "amateurporn.net",
    "amateurcommunity.com",
    "homemovies8.com",
    "homepornamateur.com",
    "home-made-videos.com",
    "milfhunter.com",
    "brokeamateurs.com",
    "petiteteens.net",
    "18abused.com",
    "tinyteens.org",
    "twistys.com", "www.twistys.com",
    "girlsdoporn.com",
    "girlsoutwest.com",
    "girlsongirls.com",
    "purepov.com",
    "povpunx.com",
    "buhake.com",
    "gloryholeswallows.com",
    "gloryholeinitiations.com",
    "gloryholeseeker.com",
    "privateisland.tv",
    "private.com", "www.private.com",
    "devilsfilm.com",
    "devil'sfilm.com",
    "devilsfilms.com",
    "houseofyre.com",
    "vivid.com", "www.vivid.com",
    "vividceleb.com",
    "fightingsluts.com",
    "czechav.com",
    "czechhunter.com",
    "czechcasting.com",
    "publicagent.com",
    "sexonthego.com",
    "moneytalks.com",
    "fakehub.com",
    "fakecop.com",
    "faketaxi.com",
    "fake-taxi.co.uk",
    "fakedrivingschool.com",
    "fakehospital.com",
    "fakeagent.com",
    "fakeagentuk.com",
    "pornstudios.com",
    "adult-empire.com", "www.adult-empire.com",
    "adultdvdempire.com", "www.adultdvdempire.com",
    "gamelink.com", "www.gamelink.com",
    "homecash.com",
    "cumfiesta.com",
    "cumbang.com",
    "cumfacials.com",
    "cumbang.net",
    "wicked temptations.com",
    "fantasticnudes.com",
    "nudography.com",
    "celeb jihad.com",
    "thefappening.so",
    "thefappeningg.com",
    "fappening.club",
    "morningfap.com",
    "fap.to",
    "fapdu.com",
    "ixxx.xxx",
    "rexxx.com",
    "giga suck.com",
    "pornrox.com",
    "pornative.com",
    "pornorama.com", "www.pornorama.com",
    "filthyrx.com",
    "pornflip.com", "www.pornflip.com",
    "xpaja.com",
    "sex-guru.net",
    "xpics.me",
    "sexygirlsnaked.org",
    "nsfwgifs.com",
    "nudepics.com",
    "porngif.com",
    "sexgif.xxx",
    "pornhd3x.com",
    "sex3.com",
    "sexu.com",
    "sexix.net",
    "pornvideosxxx.org",
    "fucktube.com",
    "fuckvideos.com",
    "fuckingpics.net",
    "freeporn.com", "www.freeporn.com",
    "freexxx.com",
    "freeadultmovies.com",
    "free-sex.com",
    "freepornvideos.com",
    "freepornhd.com",
    "freexxx.xxx",
    "freepornsex.net",
    "freepornonly.com",
    "bestfreeporn.com",
    "bestporn.com",
    "bestxxx.com",
    "topsexvideo.com",
    "topxxx.com",
    "topxxxxxx.com",
    "topfreeporn.com",
    "hornyteens.org",
    "hornywife.net",
    "hornymoms.net",
    "hornysluts.org",
    "hornymilfs.com",
    "horny.com",
    "slutty.com",
    "sluttywife.org",
    "slutwifeclub.com",
    "slutwives.com",
    "hotnakedgirls.org",
    "hotnaked.com",
    "hotnudes.com",
    "hotsexgifs.com",
    "nudeceleb.com",
    "nudecelebs.com",
    "celebskin.net",
    "mrcelebrity.net",
    "celebjihad.com",
    "aznude.com", "www.aznude.com",
    "mr.skin.com",
    "mrskin.com", "www.mrskin.com",
    "freeones.tv",
    "badgirlshd.com",
    "lesbianpornvideos.com",
    "lesbianporn.xxx",
    "lesbianporno.com",
    "bigtitspornvideos.com",
    "bigtitsporn.com",
    "bigass.xxx",
    "bigbuttporn.net",
    "roundandbrown.com",
    "brownbunnies.com",
    "whiteghetto.com",
    "blacks on blondes.com",
    "blacksonblondes.com",
    "mandingoprojects.com",
    "blacksonmoms.com",
    "blacksongils.net",
    "bbc.xxx",
    "blackcock.com",
    "blackedraw.com", "www.blackedraw.com",
    "blacked.com", "www.blacked.com",
    "tushy.com", "www.tushy.com",
    "vixen.com", "www.vixen.com",
    "deeper.com", "www.deeper.com",
    "slayed.com", "www.slayed.com",
    "blacked raw.com",
    "whorny.com",
    "twat.com",
    "hotties.com",
    "galore.com",
    "nudism.net",
    "nudistfreedom.com",
    "nudistporn.net",
    "newnudism.net",
    "youngnudism.net",
    "naturistin.com",
    "nudistas.net",
    "nudismlife.com",
    "naturist.com",
    "nudies.net",
    "nakedphotos.com",
    "maturenudists.com",
    "nudistsex.net",
    "dogging.co.uk",
    "doggingvids.com",
    "doggingvideos.co.uk",
    "gaystube.com", "www.gaystube.com",
    "gayfist.com",
    "gayporno.net",
    "gaygroupsex.com",
    "gayboystube.com",
    "gay-tube.net",
    "gaytube.com",
    "boysfood.com",
    "twinks.com",
    "twinkstube.com",
    "collegeboysphysicals.com",
    "cocksure men.com",
    "cocksuremen.com",
    "aebn.net",
    "gaybreedingwolf.com",
    "bearchive.com",
    "bearwww.com",
    "cruisingforsex.com",
    "queertube.xxx",
    "tranny.com",
    "trannytubes.com",
    "shemalesex.net",
    "tgirl.xxx",
    "transangels.com",
    "transsexual.com",
    "ladyboyxxx.com",
    "ladyboy.com",
    "futanaria.com",
    "evaflorida.com",
    "xopenload.com",
    "sexroulette.com",
    "sexchat.com", "www.sexchat.com",
    "sex-chat.net",
    "sexmessenger.com",
    "adultchat.com",
    "adultchatrooms.net",
    "adultfriendfinder.xxx",
    "adultfriendfinder.net",
    "loveaholics.com", "www.loveaholics.com",
    "benaughty.com", "www.benaughty.com",
    "together2night.com",
    "onenightfriend.com",
    "arousr.com",
    "naughtydate.com",
    "passion.com",
    "passion.network",
    "socialsex.com", "www.socialsex.com",
    "fuckswipe.com",
    "fuckbook.xxx",
    "sextpanther.com",
    "snapchat-nudes.com",
    "leakednudes.com",
    "nudesnap.com",
    "nsfwpics.com",
    "nsfwadult.com",
    "nsfw.xxx",
    "nsfwalbum.com",
    "nsfwboard.com",
    "gonewild.net",
    "gone-wild.net",
    "reddit-gonewild.com",
]

# Additional domains via common adult TLDs and patterns
ADULT_DOMAIN_PATTERNS = [
    "porn", "xxx", "sex", "nude", "naked", "adult", "hentai",
    "erotic", "milf", "cum", "fuck", "pussy", "cock", "boob",
    "tit", "ass", "anal", "oral", "bdsm", "fetish", "strip",
    "escort", "cam", "live", "hot-", "-hot", "naughty", "dirty",
]

def get_all_domains():
    """Return the complete list of adult domains."""
    return list(set(ADULT_DOMAINS))

def get_all_keywords():
    """Return the complete list of adult keywords."""
    return [kw.lower() for kw in ADULT_KEYWORDS]

def contains_adult_keyword(text: str) -> str | None:
    """
    Check if a text string contains any adult keyword.
    Uses word boundary matching to prevent false positives (e.g. 'ass' matching 'class' or 'asset').
    Returns the matched keyword if found, None otherwise.
    """
    text_lower = text.lower()
    for keyword in get_all_keywords():
        pattern = r'\b' + re.escape(keyword) + r'\b'
        if re.search(pattern, text_lower):
            return keyword
    return None
